### ISSUE TITLE
Crash on launch for 1.20.1 - 0.23-v2

### ISSUE THREAD

**Issue by Jnss98b** [BeansGalaxy/Beans-Backpacks-2#117]
![image](https://github.com/BeansGalaxy/Beans-Backpacks-2/assets/24306400/3dde5b27-6f8c-4c6e-a44e-8c0a91176833)

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-04-08 23:54:37
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'beansbackpacks'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/model/loading/v1/ModelLoadingPlugin
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.model.loading.v1.ModelLoadingPlugin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more
```

**Comment by BeansGalaxy** [comment]
I can't seem to recreate it. Is fabric API up to date? If it is and it still crashes attach the full crash report.

**Comment by Jnss98b** [comment]
I'm using fabric api 0.85.0. What's the minimum version I should install? I'm on 0.8x bc a mod I use isn't updated yet but I could try working around it if the minimum version isn't just the latest one

**Comment by Jnss98b** [comment]
Nvm the aforementioned mod has been updated for the latest fabric api and updating to the latest fabric api fixed the issue!
