### ISSUE TITLE
My game crashes when i die

### ISSUE THREAD

**Issue by AVeryLittleGhost** [BeansGalaxy/Beans-Backpacks-2#131]
Here's the crash report:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-04-22 20:51:56
Description: Ticking entity

java.lang.NoSuchFieldError: backpackInventory
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.getInventory(BeansBackpacksCompat.java:112)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.getInventory(BeansBackpacksCompat.java:97)
	at com.b1n_ry.yigd.compat.CompatComponent.<init>(CompatComponent.java:21)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.<init>(BeansBackpacksCompat.java:100)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat.getNewComponent(BeansBackpacksCompat.java:54)
	at com.b1n_ry.yigd.components.InventoryComponent.getModInventoryItems(InventoryComponent.java:124)
	at com.b1n_ry.yigd.components.InventoryComponent.<init>(InventoryComponent.java:50)
	at com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:43)
	at net.minecraft.class_1309.handler$gkb000$yigd$drop(class_1309.java:27643)
	at net.minecraft.class_1309.method_16080(class_1309.java)
	at net.minecraft.class_3222.method_6078(class_3222.java:643)
	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
	at net.minecraft.class_1657.method_5643(class_1657.java:928)
	at net.minecraft.class_3222.method_5643(class_3222.java:732)
	at net.minecraft.class_1665.method_7454(class_1665.java:374)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1665.method_5773(class_1665.java:227)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.getInventory(BeansBackpacksCompat.java:112)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.getInventory(BeansBackpacksCompat.java:97)
	at com.b1n_ry.yigd.compat.CompatComponent.<init>(CompatComponent.java:21)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat$BeansBackpacksComponent.<init>(BeansBackpacksCompat.java:100)
	at com.b1n_ry.yigd.compat.BeansBackpacksCompat.getNewComponent(BeansBackpacksCompat.java:54)
	at com.b1n_ry.yigd.components.InventoryComponent.getModInventoryItems(InventoryComponent.java:124)
	at com.b1n_ry.yigd.components.InventoryComponent.<init>(InventoryComponent.java:50)
	at com.b1n_ry.yigd.DeathHandler.onPlayerDeath(DeathHandler.java:43)
	at net.minecraft.class_1309.handler$gkb000$yigd$drop(class_1309.java:27643)
	at net.minecraft.class_1309.method_16080(class_1309.java)
	at net.minecraft.class_3222.method_6078(class_3222.java:643)
	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
	at net.minecraft.class_1657.method_5643(class_1657.java:928)
	at net.minecraft.class_3222.method_5643(class_3222.java:732)
	at net.minecraft.class_1665.method_7454(class_1665.java:374)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1665.method_5773(class_1665.java:227)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.class_1667)
	Entity ID: 18516
	Entity Name: Arrow
	Entity's Exact location: -1111.98, 79.75, 620.84
	Entity's Block location: World: (-1112,79,620), Section: (at 8,15,12 in -70,4,38; chunk contains blocks -1120,-64,608 to -1105,319,623), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,-64,512 to -1025,319,1023)
	Entity's Momentum: -0.81, -0.34, 1.20
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AVeryLittleGhost'/154, l='ServerLevel[lol]', x=-1112.79, y=78.00, z=621.70]]
	Chunk stats: 5002
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,87,0), Section: (at 0,7,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 48411 game time, 24205 day time
	Level name: lol
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 2816 (now: true), thunder time: 2145 (now: true)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 798908864 bytes (761 MiB) / 3657433088 bytes (3488 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5222
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 23003.85
	Virtual memory used (MB): 16730.15
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 246.39
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-ui-scale: Advanced UI Scaling 1.2.1-1.20.1
		advancementplaques: Advancement Plaques 1.4.11
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		auditory: Auditory 0.0.6-1.20.1
			cloth-config: Cloth Config v11 11.1.118
				cloth-basic-math: cloth-basic-math 0.6.1
		axesareweapons: Axes Are Weapons 1.7.3
		badoptimizations: BadOptimizations 2.1.0
		balm-fabric: Balm 7.2.2
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beansbackpacks: BeansBackpacks 0.24-v2
		betterdays: BetterDays 1.20.1-3.1.0.4-FABRIC
			spectrelib: SpectreLib 0.13.15+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterf3: BetterF3 7.0.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		blanket-client-tweaks: Blanket Client-tweaks 1.1.4
		boids: Boids 1.1.1
		bookshelf: Bookshelf 20.1.10
		bountiful: Bountiful 6.0.3+1.20.1
		brb: Better Recipe Book 1.10.0+1.20.0-1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.5
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.5
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.5
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.5
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.5
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.5
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.5
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.5
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.5
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.5
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.5
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.5
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.5
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.5
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.5
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.5
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.5
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		chat_heads: Chat Heads 0.10.32
		chatanimation: ChatAnimation 1.0.5
		collective: Collective 7.43
		combatroll: Combat Roll 1.3.2+1.20.1
		companion: Companion 5.1.0
		corgilib: CorgiLib 4.0.1.1
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		cpm: Customizable Player Models 0.6.16b
		creeperoverhaul: Creeper Overhaul 3.0.2
			resourcefullib: Resourceful Lib 2.1.20
				com_teamresourceful_bytecodecs: bytecodecs 1.0.2
				com_teamresourceful_yabn: yabn 1.0.3
		crops_love_rain: Crops Love Rain 1.4.0
			cactusconfig: Cactus Config 2.1.1+knot+1.20.1
		ctov: ChoiceTheorem's Overhauled Village 3.4.3
		cupboard: cupboard 1.20.1-2.5
		deathfinder: Death Finder 8.0.1
		doubledoors: Double Doors 5.5
		dragonfight: Dragonfight Mod 1.20.1-4.3
		dsurround: Dynamic Surroundings 0.3.3
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.4
		dungeons_arise: When Dungeons Arise 2.1.58
		dynamic_fps: Dynamic FPS 3.4.2
		eatinganimationid: Eating Animation 1.20+1.9.61
		elytraslot: Elytra Slot 6.3.0+1.20.1
		enchdesc: EnchantmentDescriptions 17.0.14
		endermanoverhaul: Enderman Overhaul 1.0.4
		endrem: End Remastered 5.2.4
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 2.0
		entity_texture_features: Entity Texture Features 6.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.18+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.6
		ferritecore: FerriteCore 6.0.1
		firstperson: FirstPerson 2.3.4
		fog-looks-good-now: FogLooksGoodNow 2.2.0+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		friendlyfire: FriendlyFire 18.0.6
		friendsandfoes: Friends&Foes 2.0.10
		geckolib: GeckoLib 4 4.4.2
			com_eliotlash_mclib_mclib: mclib 20
		guarding: Guarding 2.4.0
			mm: Manningham Mills 2.3
			scribe: Scribe 1.20.1-0.5.0-alpha
		guardvillagers: GuardVillagers 2.0.9-1.20.1
			midnightlib: MidnightLib 1.4.1
		held-item-info: Held Item Info 1.5.0
		hopobetterruinedportal: Hopo Better Ruined Portal 1.3.7
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.4
		horseshoes: Horseshoes 1.0.2
		hotbarcycle: Hotbar Cycle 1.1.2
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.11+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: Jump Over Fences 1.3.1
		kambrik: Kambrik 6.1.1+1.20.1
		kiwi: Kiwi Library 11.6.2
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		leafmealone: Leaf Me Alone 1.0.0
		leavesbegone: Leaves Be Gone 8.0.0
		legendarytooltips: Legendary Tooltips 1.4.5
		lithium: Lithium 0.11.2
		logical_zoom: Logical Zoom 0.0.20
		majruszlibrary: Majrusz Library 7.0.5
		majruszsdifficulty: Majrusz's Progressive Difficulty 1.9.9
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.5.2-1.20
			maelstrom_library: Maelstrom Library 1.6.1-1.20
		modernfix: ModernFix 5.16.1+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.11.12
		mr_villager_transportation: Villager Transportation 1.2
		mru: Mineblock's Repeated Utilities 0.4.0+1.20
		musicplayer: Music Player 2.7.0.236
		mutantmonsters: Mutant Monsters 8.0.7
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			extensibleenums: Extensible Enums 7.0.1
		mvs: Moog's Voyager Structures 4.1.2-1.20-fabric
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		no-telemetry: No Telemetry 1.8.0
		noanimaltemptdelay: No Animal Tempt Delay 1.1
		noisium: Noisium 2.0.2+mc1.20-1.20.1
		nyfsspiders: Nyf's Spiders 2.1.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		presencefootsteps: Presence Footsteps 1.9.3
			kirin: Kirin UI 1.15.6+1.20.1
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.1.17
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		resourcefulconfig: Resourcefulconfig 2.1.2
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		smarterfarmers: Smarter Farmers 1.20-1.8.2
		smoothswapping: Smooth Swapping 0.9.3.1
		snowundertrees: Snow Under Trees 2.2.0+1.20.1
			yet_another_config_lib_v3: YetAnotherConfigLib 3.2.2+1.20
				com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		sodium: Sodium 0.5.8+mc1.20.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		stackrefill: Stack Refill 4.2
		status-effect-bars: Status Effect Bars 1.0.3
		stepitup: StepItUp 2.0.1-1.20.1
		tectonic: Tectonic 2.3.4
		tenshilib: TenshiLib 1.20.1-1.7.6
		terralith: Terralith 2.4.11
		trashslot: TrashSlot 15.1.0
		trinkets: Trinkets 3.7.2
		uteamcore: U Team Core 5.1.4.269
		villagernames: Villager Names 7.3
		visuality: Visuality 0.7.1+1.20
		wakes: Wakes 0.2.4+1.20.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 1.14.0
		waystones: Waystones 14.1.3
		yigd: You're in Grave Danger 2.0.0-beta.11
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		yungsapi: YUNG's API 1.20-Fabric-4.0.4
			org_javassist_javassist: javassist 3.29.2-GA
	Loaded Shaderpack: Complementary Reimagined v5.1.1.zip
		Profile: VERYLOW (+1 option changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['AVeryLittleGhost'/154, l='ServerLevel[lol]', x=-1112.79, y=78.00, z=621.70]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, tectonic/terratonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.7-1.20.1

**Comment by BeansGalaxy** [comment]
Your In Grave Danger is causing my mod to crash. A recent update broke compatibility and I can't fix it on my end. Hopefully he'll fix it in version beta12 of his mod but until then I can't do anything about it.

**Comment by AVeryLittleGhost** [comment]
> Your In Grave Danger is causing my mod to crash. A recent update broke compatibility and I can't fix it on my end. Hopefully he'll fix it in version beta12 of his mod but until then I can't do anything about it.

ohhh, kk thanks
