### ISSUE TITLE
Owner is null exception

### ISSUE THREAD

**Issue by duarm** [BeansGalaxy/Beans-Backpacks-2#132]
The error hapens when me and my friend are at the server at the same time, we played normally for some hours, but something broke along the way

Version  1.20.1 0.25-v2

I have Trinkets
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5667()" because "owner" is null
	at com.beansgalaxy.backpacks.network.clientbound.SyncBackSlot.send(SyncBackSlot.java:30) ~[BeansBackpacks-fabric-1.20.1-0.25-v2.jar:?]
	at com.beansgalaxy.backpacks.network.serverbound.CallBackSlot.handle(CallBackSlot.java:36) ~[BeansBackpacks-fabric-1.20.1-0.25-v2.jar:?]
	at com.beansgalaxy.backpacks.network.NetworkPackages.lambda$register2S$0(NetworkPackages.java:15) ~[BeansBackpacks-fabric-1.20.1-0.25-v2.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.minecraft.class_3244.handler$cij000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2000) ~[server-intermediary.jar:?]
...
```

**Comment by augustsaintfreytag** [comment]
I have the same crash, happens for me when I am logged in and another player joins, then we both crash back to the menu.

**Comment by BeansGalaxy** [comment]
This is a networking error in Fabric. Your game is asking the server to send over another player's back slot but for some reason the server forgets who's back slot to look for. I can't seem to figure out why it's forgetting but I'll have a fix in the next update

**Comment by VitaminJake** [comment]
We had the same issue, kill the player who is crashing the game (if possible); or else uninstall the mod, then have them join, then reinstall, then go about as normal. Particularly the ender backpack seems to be the culprit for us.

**Comment by duarm** [comment]
> We had the same issue, kill the player who is crashing the game (if possible); or else uninstall the mod, then have them join, then reinstall, then go about as normal. Particularly the ender backpack seems to be the culprit for us.

We don't have an ender backpack, so we can rule this one out

**Comment by BeansGalaxy** [comment]
I was hoping to release a quick fix for this bug but it's taking much longer than I thought. I am working on a fix but can't find a solution just yet. The tricky thing is ensuring the client has loaded the player before unpacking the data for the back slot. If not then your game crashes.

Almost there though.

**Comment by BeansGalaxy** [comment]
Version 20.1-0.26-v2 has a fix for this! Thanks for all your reports and patience ;)
