### ISSUE TITLE
cant upgrade 2 netherite 

### ISSUE THREAD

**Issue by JokiSTM** [BeansGalaxy/Beans-Backpacks-2#14]
tried upgrading an iron backpack 2 netherite and it crashes my game EVERY time
A detailed walkthrough of the error, its code path and all known details is as follows:
[11/01/2024 22:40:33 PM] ---------------------------------------------------------------------------------------
[11/01/2024 22:40:33 PM]
[11/01/2024 22:40:33 PM] -- Head --
[11/01/2024 22:40:33 PM] Thread: Render thread
[11/01/2024 22:40:33 PM] Stacktrace:
[11/01/2024 22:40:33 PM] at com.beansgalaxy.backpacks.items.RecipeSmithing.method_8116(RecipeSmithing.java:74)
[11/01/2024 22:40:33 PM] at net.minecraft.class_4862.method_24928(class_4862.java:101)
[11/01/2024 22:40:33 PM] at net.minecraft.class_4861.method_7609(class_4861.java:106)
[11/01/2024 22:40:33 PM] at net.minecraft.class_4861$3.method_5431(class_4861.java:96)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1277.redirect$cki000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:543)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1277.method_5447(class_1277.java:144)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1735.method_7673(class_1735.java:75)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1735.method_48931(class_1735.java:66)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1735.method_53512(class_1735.java:63)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1735.method_32755(class_1735.java:160)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1703.method_30010(class_1703.java:412)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1703.method_7593(class_1703.java:294)
[11/01/2024 22:40:33 PM] at net.minecraft.class_636.method_2906(class_636.java:450)
[11/01/2024 22:40:33 PM] at net.minecraft.class_465.method_2383(class_465.java:552)
[11/01/2024 22:40:33 PM] at net.minecraft.class_465.method_25406(class_465.java:516)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_1605(class_312.java:101)
[11/01/2024 22:40:33 PM] at net.minecraft.class_437.method_25412(class_437.java:414)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_1601(class_312.java:101)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_22686(class_312.java:180)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1255.execute(class_1255.java:102)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_22684(class_312.java:180)
[11/01/2024 22:40:33 PM] at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[11/01/2024 22:40:33 PM] at org.lwjgl.system.JNI.invokeV(Native Method)
[11/01/2024 22:40:33 PM] at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[11/01/2024 22:40:33 PM] at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[11/01/2024 22:40:33 PM] at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[11/01/2024 22:40:33 PM]
[11/01/2024 22:40:33 PM] -- Click info --
[11/01/2024 22:40:33 PM] Details:
[11/01/2024 22:40:33 PM] Menu Type: minecraft:smithing
[11/01/2024 22:40:33 PM] Menu Class: net.minecraft.class_4862
[11/01/2024 22:40:33 PM] Slot Count: 40
[11/01/2024 22:40:33 PM] Slot: 2
[11/01/2024 22:40:33 PM] Button: 1
[11/01/2024 22:40:33 PM] Type: PICKUP
[11/01/2024 22:40:33 PM] Stacktrace:
[11/01/2024 22:40:33 PM] at net.minecraft.class_1703.method_7593(class_1703.java:294)
[11/01/2024 22:40:33 PM] at net.minecraft.class_636.method_2906(class_636.java:450)
[11/01/2024 22:40:33 PM] at net.minecraft.class_465.method_2383(class_465.java:552)
[11/01/2024 22:40:33 PM] at net.minecraft.class_465.method_25406(class_465.java:516)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_1605(class_312.java:101)
[11/01/2024 22:40:33 PM] at net.minecraft.class_437.method_25412(class_437.java:414)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_1601(class_312.java:101)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_22686(class_312.java:180)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1255.execute(class_1255.java:102)
[11/01/2024 22:40:33 PM] at net.minecraft.class_312.method_22684(class_312.java:180)
[11/01/2024 22:40:33 PM] at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[11/01/2024 22:40:33 PM] at org.lwjgl.system.JNI.invokeV(Native Method)
[11/01/2024 22:40:33 PM] at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
[11/01/2024 22:40:33 PM] at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
[11/01/2024 22:40:33 PM] at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
[11/01/2024 22:40:33 PM] at net.minecraft.class_1041.method_15998(class_1041.java:287)
[11/01/2024 22:40:33 PM] at net.minecraft.class_310.method_1523(class_310.java:1297)
[11/01/2024 22:40:33 PM] #@!@# Game crashed! Crash report saved to: #@!@#

**Comment by BeansGalaxy** [comment]
Not sure what could be happening, update v2-0.1 (1.20.1) and v2-0.7 (1.20.2) has new code for the backpack recipes so if this happens post your crash report
