### ISSUE TITLE
Game Crashes when opening backpack on the ground, only on multiplayer and when the backpack has over 3 rows of items

### ISSUE THREAD

**Issue by LadyStrella** [BeansGalaxy/Beans-Backpacks-2#144]
[21:33:38] [Netty Epoll Client IO #0/ERROR]: Encountered exception while handling in channel with name "beansbackpacks:sync_back_inv_c"
java.lang.NullPointerException: Cannot read field "field_7512" because "player" is null
	at com.beansgalaxy.backpacks.client.network.CommonAtClient.syncBackInventory(CommonAtClient.java:49) ~[BeansBackpacks-fabric-1.20.1-0.27-v2.jar:?]
	at com.beansgalaxy.backpacks.network.clientbound.SendBackInventory.handle(SendBackInventory.java:64) ~[BeansBackpacks-fabric-1.20.1-0.27-v2.jar:?]
	at com.beansgalaxy.backpacks.network.NetworkPackages.lambda$register2C$1(NetworkPackages.java:22) ~[BeansBackpacks-fabric-1.20.1-0.27-v2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.minecraft.class_634.handler$ddp000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3768) ~[client-intermediary.jar:?]

**Comment by BeansGalaxy** [comment]
Super simple mistake, should be releasing a new version tomorrow.

**Comment by BeansGalaxy** [comment]
0.28-v2 is live with the patch! Enjoy :)
