### ISSUE TITLE
Unknown serializer type 807 when placing items into backpack

### ISSUE THREAD

**Issue by ArkVeil** [BeansGalaxy/Beans-Backpacks-2#176]
[latest.log](https://github.com/user-attachments/files/16076398/latest.log)

When trying to place items into a backpack that is placed down, all clients within loaded range disconnect with the error

Unknown serializer type 807

**Comment by ArkVeil** [comment]
Happens when just placing down the backpack sometimes. I placed my backpack down and it disconnected my friend. I think the server to client packet is being mangled.

**Comment by rydens** [comment]
Hello! Having probably the same issue here, on 1.20.1, Quilt & Fabric. One player places down a regular backpack and places something inside, they and everyone else nearby gets kicked (but no crashes!) with the same error:

```
[Netty Epoll Client IO #0/ERROR]: Exception occurred in netty pipeline io.netty.handler.codec.DecoderException: Unknown serializer type 813
	at net.minecraft.class_2945$class_7834.method_46362(class_2945.java:233) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2739.method_46616(class_2739.java:32) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2739.<init>(class_2739.java:16) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:459) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:522) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[minecraft-1.20.1.i0:0/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
...
```
[Log at issue](https://mclo.gs/bdNYIjO#L6371) (don't mind the gamescope garbage, this same issue happens for clients on Linux, macOS, and Windows)

The server log just shows a regular disconnect.
