### ISSUE TITLE
[Bug] crashed while using a cauldron inventory, can't log into server

### ISSUE THREAD

**Issue by nopeless** [BeansGalaxy/Beans-Backpacks-2#207]
https://github.com/BeansGalaxy/Beans-Backpacks-2/blob/7ac7a03e9951e62689ffcd7753fd887dc15b4f77/common/src/main/java/com/beansgalaxy/backpacks/client/renderer/features/CauldronFeature.java#L77-L86

I know you are busy, so I won't ask for a fix, but line 82 is causing me to not log-in to a server.

I'm leaving this here so that if you do pick this project up again you can look into this and make a proper fix

```text
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1321) ~[?:?] {}
	at java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1235) ~[?:?] {}
	at net.minecraft.client.renderer.texture.TextureAtlas.m_118316_(TextureAtlas.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23526!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.beansgalaxy.backpacks.platform.ForgeCompatHelper.getFluidTexture(ForgeCompatHelper.java:65) ~[BeansBackpacks-forge-1.20.1-2.0.2.jar%23355!/:2.0.2] {re:classloading}
	at com.beansgalaxy.backpacks.client.renderer.features.CauldronFeature.render(CauldronFeature.java:82) ~[BeansBackpacks-forge-1.20.1-2.0.2.jar%23355!/:2.0.2] {re:classloading}
	at com.beansgalaxy.backpacks.client.renderer.features.BackFeature.render(BackFeature.java:63) ~[BeansBackpacks-forge-1.20.1-2.0.2.jar%23355!/:2.0.2] {re:classloading}
	at com.beansgalaxy.backpacks.client.renderer.features.BackFeature.m_6494_(BackFeature.java:19) ~[BeansBackpacks-forge-1.20.1-2.0.2.jar%23355!/:2.0.2] {re:classloading}
	
```

**Comment by nopeless** [comment]
update: issue is slightly related to mod incompatibility

**Comment by Bruskych** [comment]
Do you know where the author of the mod disappeared to?

**Comment by nopeless** [comment]
> Do you know where the author of the mod disappeared to?

no @Vladyslav1728
