### ISSUE TITLE
When using anvil to change name of BenBackpack server crashed

### ISSUE THREAD

**Issue by KimDonghyeok** [BeansGalaxy/Beans-Backpacks-2#32]
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-01-22 15:05:04
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at com.beansgalaxy.backpacks.items.BackpackItem.method_7864(BackpackItem.java:192)
	at net.minecraft.class_1799.method_7964(class_1799.java:594)
	at net.minecraft.class_1706.method_24928(class_1706.java:291)
	at net.minecraft.class_1706.method_7625(class_1706.java:367)
	at net.minecraft.class_3244.method_12060(class_3244.java:646)
	at net.minecraft.class_2855.method_12408(class_2855.java:24)
	at net.minecraft.class_2855.method_11054(class_2855.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 725621360 bytes (692 MiB) / 1426063360 bytes (1360 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2786
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x164e
	Graphics card #1 versionInfo: DriverVersion=31.0.22024.3
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 41108.98
	Virtual memory used (MB): 28420.66
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 167.88
	JVM Flags: 1 total; -Xmx6G
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		another_furniture: Another Furniture 1.20.1-3.0.1
		architectury: Architectury 9.1.12
		backpacked: Backpacked 2.2.7
		bakery: Bakery 1.1.3
		beansbackpacks: BeansBackpacks 0.5-v2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		cakedelight: Cake Delight 1.20.1-v3.0.2
		candlelight: Candlelight 1.2.8
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 7.30
		convenientdecor: Convenient Decor 0.3.0
		coroutil: CoroUtil 1.20.1-1.3.5
		decorative_blocks: Decorative Blocks 4.0.2
		doapi: Lets Do Api 1.2.8
			blue_endless_jankson: jankson 1.2.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		doubledoors: Double Doors 5.2
		elytraslot: Elytra Slot 6.3.0+1.20.1
		emojiful: Emojiful 4.2.0
			com_esotericsoftware_yamlbeans_yamlbeans: yamlbeans 1.15
			midnightlib: MidnightLib 1.1.0
		expandeddelight: Expanded Delight 0.3.0.2
		exposure: Exposure 1.2.2
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		ferritecore: FerriteCore 6.0.1
		festive_delight: Festive Delight 1.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		frightsdelight: Frights Delight 1.20.1-1.0.1
		genshinstrument: Genshin Instruments 3.4
		herbalbrews: Herbal Brews 1.0.2
		jade: Jade 11.7.0
		jadeaddons: Jade Addons 5.2.3
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.18
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		labellingcontainers: Labelling Containers 1.3.1
		leavesbegone: Leaves Be Gone 8.0.0
		lithium: Lithium 0.11.2
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.1.0
		mcwfurnitures: Macaw's Furniture 3.2.2
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwtrpdoors: Macaw's Trapdoors 1.1.2
		mcwwindows: Macaw's Windows 2.2.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.8.84
		niftycarts: NiftyCarts 3.0.0+1.20.1
		oceansdelight: Ocean's Delight fabric-1.0.2-1.20
		puzzleslib: Puzzles Lib 8.1.13
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		recipe-book-delight: Recipe Book Delight 0.3.0-1.20
			dark-matter-base: Dark Matter Base 2.2.0-1.20
			dark-matter-enums: Dark Matter Enums 2.2.0-1.20
			dark-matter-minecraft: Dark Matter Minecraft 2.2.0-1.20
			dark-matter-recipe-book: Dark Matter Recipe Book 2.2.0-1.20
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.2
		sleepwarp: SleepWarp 2.2.0_rc1+1.20.1
		smwyg: Show Me What You Got 1.1.1
		spark: spark 1.10.53
		starlight: Starlight 1.1.2+fabric.dbc156f
		styled-nicknames: Styled Nicknames 1.2.1+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.2+1.19.3
			player-data-api: Player Data API 0.2.2+1.19.3
		terrablender: TerraBlender 3.0.1.2
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		trinkets: Trinkets 3.7.1
		utilitybelt: Utility Belt 1.3.6+1.20.1
		vinery: Vinery 1.4.7
		watut: What Are They Up To 1.20.1-1.0.12
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
	Server Running: true
	Player Count: 1 / 20; [class_3222['Qoophon'/230, l='ServerLevel[world]', x=8.50, y=71.00, z=14.29]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

here is crash reports and my server is fabric 0.15.3 server / minecraft 1.20.1

you can download server file link below
https://fabricmc.net/use/server/

**Comment by BeansGalaxy** [comment]
Server was trying to call a method in a client only class I moved there for testing and forgot to move back, this'll be fixed in 0.6-v2. (oops)
