### ISSUE TITLE
Beans Backpacks appears to be softlocking/constantly disconnecting players Fabric 1.20.1

### ISSUE THREAD

**Issue by JAYDEMITE** [BeansGalaxy/Beans-Backpacks-2#48]
Seems to disconnect them, doesn't seem to matter if the backpack is in their inventory or has items in it or what. It is just causing some form of issue.

[Server thread/WARN]: Failed to handle packet for /[PLAYERS IP]
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArithmeticException: / by zero
        at com.beansgalaxy.backpacks.core.BackpackInventory.insertItemSilent(BackpackInventory.java:188) ~[BeansBackpacks-fabric-1.20.1-0.7-v2.jar:?]
        at net.minecraft.class_1661.handler$zhb000$beansbackpacks$insertBackpack(class_1661.java:1816) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7367(class_1661.java:287) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7394(class_1661.java:263) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.method_5694(class_1542.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7341(class_1657.java:627) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:600) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more

**Comment by BeansGalaxy** [comment]
Looks like I'm trying to divide by zero. I just put a simple check to make sure the number isn't zero before dividing but I think its happening because you're picking up an item that stacks to 0 (like how ender pearls stack to 16) which is very weird to begin with. I'll have this fixed in 20.1-0.11-v2 & 20.2-0.14-v2
