### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lostopkk** [BeansGalaxy/Beans-Backpacks-2#57]
[22:26:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: dev/sterner/guardvillagers/common/entity/GuardEntity
	at settingdust.heraclesforvillagers.EntrypointKt.init$lambda$0(Entrypoint.kt:30) ~[HeraclesForVillagers-0.3.1+sha.401648a.jar:?]
	at net.fabricmc.fabric.api.event.player.UseEntityCallback.lambda$static$0(UseEntityCallback.java:57) ~[fabric-events-interaction-v0-0.6+1802ada577-41aa849bfa453c20.jar:?]
	at net.minecraft.class_3244$1.handler$bdb000$fabric-events-interaction-v0$onPlayerInteractEntity(class_3244.java:1715) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34220(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2824$class_5910.method_34213(class_2824.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1571) ~[client-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.sterner.guardvillagers.common.entity.GuardEntity
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 23 more

**Comment by BeansGalaxy** [comment]
This looks like an error for "guardvillagers". If you have the full log or what might be causing this post it here too but I'm closing this issue since this doesn't relate or point to any code from my mod.
