### ISSUE TITLE
Crash when opening keybinds in options

### ISSUE THREAD

**Issue by owosoup** [BeansGalaxy/Beans-Backpacks-2#65]
When opening the keybinds menu, the game crashes (in a world, or in the main menu).

Relevant logs:
`[16:59:00] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.23.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.23.1.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_459$class_462 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:459) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_6599.method_25426(class_6599.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_458.method_19872(class_458.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_6599.method_25426(class_6599.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_458.method_19872(class_458.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect(Lnet/minecraft/class_4185;Lnet/minecraft/class_7919;)V in #beansbackpacks:beansbackpacks.mixins.json:client.KeyBindTooltip from mod beansbackpacks failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap beansbackpacks.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.23.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.23.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_6599.method_25426(class_6599.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_458.method_19872(class_458.java:29) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 18 more`

Full log: [https://mclo.gs/W0YAa5D](url)
(I have a lot of mods, mea culpa.)

**Comment by BeansGalaxy** [comment]
I'll check this out. Labeled under compatibility for now since I assume its's an issue with another mod trying to redirect the same method.

**Comment by owosoup** [comment]
Update : it's indeed my modpack. I'll have to find the mod in question, and see with the other author as well.

**Comment by BeansGalaxy** [comment]
Have you found the mod causing the problem? If not send me that log again, the link expired. If it is just a redirect causing the issue I can try to disable it while that mod's installed.

**Comment by owosoup** [comment]
I found the incompatible mod! It's Tap Tab on [modrinth](modrinth.com/mod/tap-tab) / [github](github.com/KrLite/Mod.Tap-Tab)
Here's the last log before I found the issue, I just went in blind and disabled half my mods repeatedly. [pastebin.pl/view/d91f71b3](https://pastebin.pl/view/d91f71b3)
I'm nooot quite sure why it happens, and I'm not a dev, so I can't speculate.
Tap Tab is just a mod that makes your inventory cycle bars down when you tap TAB twice. So your hotbar becomes the upper bar in your inventory, like scrolling down/cycling it. It makes sense that a GUI-related mod conflicts, considering you introduced your own UI inventory in your mod (my dark inventory resource pack didn't interact with the white default texture!) when dropping the backpack and opening it, looks super cool with the 3D model anim! It's my best (uneducated) guess.

**Comment by owosoup** [comment]
Oops. I didn't mean to close this. Well it's not really your fault either so I could close it for good maybe?

**Comment by BeansGalaxy** [comment]
I see the problem. If you're curious, Minecraft says when hovering over a key bind button in the key bind menu there isn't any text unless this key is bound to something else. Me and Tap Tab are both telling minecraft that it should be something different, minecraft can't decide who to listen to and "*craps the bed*" if you will.

I don't know how to disable my code while Tap Tab is enabled but I know it's possible so I'll have it fixed when ***20.1***-0.16-v2 is posted

**Comment by BeansGalaxy** [comment]
Thanks! If you're curious we were both replacing the same line of minecraft's code and minecraft couldn't decide which version to choose.

Plus I wrote that code when I had less of an understanding of how to directly change minecraft's code so now I have a safe way that wont crash in the future. Thanks again! Should be fixed in version <ins>20.1</ins>-0.16-v2
